--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(1, 'afcab9ae-4815-11e6-beb8-9e71128cae78', 'Prepare Runtime Environment', 1, 'INTEGRATION', true, NULL, 'PREPARE_RUNTIME', 1, 1, NULL, '{"ActivityExecutionID":"${ActivityExecutionID}","EventToTrigger":"LOAD_FILE","workflowFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\PentahoFiles\\prepare-runtime-enviorment.kjb","workflowType":"Job","inputParameters":{"ActivityExecutionID":"${ActivityExecutionID}","BaseFolderPath":"${BaseFolderPath}","SubscriberID":"${SubscriberID}","IntegrationProcessExecutionID":"${IntegrationProcessExecutionID}","IntegrationProcessID":"${IntegrationProcessID}","SourceFile":"${sourceFilePath}"},"outputParameters":[]}',NULL, 'MANUAL');
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(2, '66daed12-4cd0-11e6-beb8-9e71128cae77', 'Load file in Database', 2, 'INTEGRATION', false, NULL, 'LOAD_FILE', 1, 1, NULL, '{  	"ActivityExecutionID": "${ActivityExecutionID}",  	"workflowFilePath": "${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\PentahoFiles\\load-prospect-universe-data.ktr",  	"StepToTrigger": 3,  	"workflowType": "Transformation",  	"inputParameters": {  		"InputFileName": "${SourceFilePath}",  		"ActivityExecutionID": "${ActivityExecutionID}",  		"SubscriberID": "${SubscriberID}",  		"IntegrationProcessExecutionID": "${IntegrationProcessExecutionID}",  		"IntegrationProcessID": "${IntegrationProcessID}"  	},  	"outputParameters": []  }', NULL, 'MANUAL');
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(3, '771d242e-4cd0-11e6-beb8-9e71128cae77', 'End execution', 3, 'END', false, NULL, 'END_EXECUTION', 2, 1, NULL, '{}', NULL, 'MANUAL');
--
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(4, 'ecc198da-07f7-4d38-bf69-6a38b2a04dfa', 'Prepare Runtime Environment', 1, 'INTEGRATION', true, NULL, 'PREPARE_RUNTIME', 1, 2, NULL, '{"ActivityExecutionID":"${ActivityExecutionID}","StepToTrigger":2,"workflowFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\PentahoFiles\\prepare-runtime-enviorment.kjb","workflowType":"Job","inputParameters":{"ActivityExecutionID":"${ActivityExecutionID}","BaseFolderPath":"${BaseFolderPath}","SubscriberID":"${SubscriberID}","IntegrationProcessExecutionID":"${IntegrationProcessExecutionID}","IntegrationProcessID":"${IntegrationProcessID}","SourceFile":"${sourceFilePath}"},"outputParameters":[]}','{"cronExpression":"0 0/5 * * * ?"}', 'SCHEDULED');
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(5, '9868c673-0d21-4b9d-8d7e-4526439175f8', 'Copy file from FTP', 2, 'INTEGRATION', false, NULL, 'COPY_FILE', 1, 2, NULL, '{  	"ActivityExecutionID": "${ActivityExecutionID}",  	"workflowFilePath": "${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\PentahoFiles\\copy-file-from-ftp.kjb",  	"StepToTrigger": 3,  	"workflowType": "Job",  	"inputParameters": {  "ActivityExecutionID": "${ActivityExecutionID}",  		"SubscriberID": "${SubscriberID}",  		"IntegrationProcessExecutionID": "${IntegrationProcessExecutionID}", "IntegrationProcessID": "${IntegrationProcessID}"  	},  	"outputParameters": []  }', NULL, 'MANUAL');
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(6, '9868c673-0d21-4b9d-8d7e-4526439175f8', 'Load file in Database', 3, 'INTEGRATION', false, NULL, 'LOAD_FILE', 1, 2, NULL, '{  	"ActivityExecutionID": "${ActivityExecutionID}",  	"workflowFilePath": "${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\PentahoFiles\\load-prospect-universe-data.ktr",  	"StepToTrigger": 4,  	"workflowType": "Transformation",  	"inputParameters": {  		"InputFileName": "${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\Exec_${IntegrationProcessExecutionID}\\Input\\Input.${IntegrationProcessExecutionID}.csv",  		"ActivityExecutionID": "${ActivityExecutionID}",  		"SubscriberID": "${SubscriberID}",  		"IntegrationProcessExecutionID": "${IntegrationProcessExecutionID}",  "IntegrationProcessID": "${IntegrationProcessID}"  	},  	"outputParameters": []  }', NULL, 'MANUAL');
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(7, '9ba0c8a7-e418-40e8-881e-41920a122645', 'End execution', 4, 'END', false, NULL, 'END_EXECUTION', 2, 2, NULL, '{}', NULL, 'MANUAL');
--
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(8, '7667d91c-d24e-11e6-bf26-cec0c932ce01', 'Prepare Runtime Environment', 1, 'INTEGRATION', true, NULL, 'PREPARE_RUNTIME', 1, 3, NULL, '{"ActivityExecutionID":"${ActivityExecutionID}","StepToTrigger":2,"workflowFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\PentahoFiles\\prepare-runtime-enviorment.kjb","workflowType":"Job","inputParameters":{"ActivityExecutionID":"${ActivityExecutionID}","BaseFolderPath":"${BaseFolderPath}","SubscriberID":"${SubscriberID}","IntegrationProcessExecutionID":"${IntegrationProcessExecutionID}","IntegrationProcessID":"${IntegrationProcessID}","SourceFile":"${sourceFilePath}"},"outputParameters":[]}','{"cronExpression":"0 0/35 * * * ?"}', 'SCHEDULED');
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(9, '7d82a1e6-d24e-11e6-bf26-cec0c932ce01', 'Load neo4j Data', 2, 'INTEGRATION', false, NULL, 'LOAD_NEO4J_DATA', 1, 3, NULL, '{  	"ActivityExecutionID": "${ActivityExecutionID}",  	"workflowFilePath": "${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\PentahoFiles\\test.ktr",  	"StepToTrigger": 3,  	"workflowType": "Transformation",  	"inputParameters": {"siteFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\Input\\site.csv","wastageFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\Input\\wastageDamageExpired.csv" },  	"outputParameters": []  }', NULL, 'MANUAL');
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(10, '9ba0c8a7-e418-40e8-881e-41920a122645', 'End execution', 3, 'END', false, NULL, 'END_EXECUTION', 1, 3, NULL, '{}', NULL, 'MANUAL');
--
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(11, 'a92fa8c2-d7dd-11e6-bf26-cec0c932ce01', 'Prepare Runtime Environment', 1, 'INTEGRATION', true, NULL, 'PREPARE_RUNTIME', 1, 4, NULL, '{"ActivityExecutionID":"${ActivityExecutionID}","StepToTrigger":2,"workflowFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\PentahoFiles\\prepare-runtime-enviorment.kjb","workflowType":"Job","inputParameters":{"ActivityExecutionID":"${ActivityExecutionID}","BaseFolderPath":"${BaseFolderPath}","SubscriberID":"${SubscriberID}","IntegrationProcessExecutionID":"${IntegrationProcessExecutionID}","IntegrationProcessID":"${IntegrationProcessID}","SourceFile":"${sourceFilePath}"},"outputParameters":[]}','{"cronExpression":"0 0/35 * * * ?"}', 'SCHEDULED');
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(12, 'af5c7446-d7dd-11e6-bf26-cec0c932ce01', 'Load Item into MySQL', 2, 'INTEGRATION', false, NULL, 'LOAD_MYSQL_DATA', 1, 4, NULL, '{  	"ActivityExecutionID": "${ActivityExecutionID}",  	"workflowFilePath": "${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\PentahoFiles\\Sidel_item_Load.ktr",  	"StepToTrigger": 3,  	"workflowType": "Transformation",  	"inputParameters": {"SidelItemCsvPath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\Input\\sidel_item.csv" },  	"outputParameters": []  }', NULL, 'MANUAL');
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(13, 'b6cac4a8-d7dd-11e6-bf26-cec0c932ce01', 'End execution', 3, 'END', false, NULL, 'END_EXECUTION', 1, 4, NULL, '{}', NULL, 'MANUAL');


--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(14, '7767d91c-d24e-11e6-bf26-cec0c932ce01', 'Prepare Runtime Environment', 1, 'INTEGRATION', true, NULL, 'PREPARE_RUNTIME', 1, 5, NULL, '{"ActivityExecutionID":"${ActivityExecutionID}","StepToTrigger":2,"workflowFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\PentahoFiles\\prepare-runtime-enviorment.kjb","workflowType":"Job","inputParameters":{"ActivityExecutionID":"${ActivityExecutionID}","BaseFolderPath":"${BaseFolderPath}","SubscriberID":"${SubscriberID}","IntegrationProcessExecutionID":"${IntegrationProcessExecutionID}","IntegrationProcessID":"${IntegrationProcessID}","SourceFile":"${sourceFilePath}"},"outputParameters":[]}','{"cronExpression":"0 0/35 * * * ?"}', 'SCHEDULED');

--MANUAL (change the ACTIVITYID IF NEEDED)
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(14, '7e82a1e6-d24e-11e6-bf26-cec0c932ce01', 'Load neo4j Data', 1, 'INTEGRATION', true, NULL, 'LOAD_NEO4J_DATA', 1, 5, NULL, '{  	"ActivityExecutionID": "${ActivityExecutionID}",  	"workflowFilePath": "${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\PentahoFiles\\csv-to-neo4j-copy-JNDI.ktr",  	"StepToTrigger": 2,  	"workflowType": "Transformation", "inputParameters": {"siteFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\Input\\site.csv","wastageFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\Input\\wastageDamageExpired.csv" },  	"outputParameters": []  }', NULL, 'MANUAL');
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(15, '9ca0c8a7-e418-40e8-881e-41920a122645', 'End execution', 2, 'END', false, NULL, 'END_EXECUTION', 1, 5, NULL, '{}', NULL, 'MANUAL');

--Scheduler (change the ACTIVITYID IF NEEDED)
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(16, '7e82a1e6-d24e-11e6-bf26-cec0c932ce01', 'Load neo4j Data', 1, 'INTEGRATION', true, NULL, 'LOAD_NEO4J_DATA', 1, 5, NULL, '{  	"ActivityExecutionID": "${ActivityExecutionID}",  	"workflowFilePath": "${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\PentahoFiles\\csv-to-neo4j-copy-JNDI.ktr",  	"StepToTrigger": 2,  	"workflowType": "Transformation", "inputParameters": {"siteFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\Input\\site.csv","wastageFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\Input\\wastageDamageExpired.csv" },  	"outputParameters": []  }', '{"cronExpression":"0 0 1 1 * ?"}', 'SCHEDULED');
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex,  ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(17, '9ca0c8a7-e418-40e8-881e-41920a122645', 'End execution', 2, 'END', false, NULL, 'END_EXECUTION', 1, 5, NULL, '{}', NULL, 'MANUAL');

--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(1,'f27e88b9-ab31-4bc1-a41b-de874e635df1','SampleFileTransformation',1,'INTEGRATION',TRUE,'2019-06-14 16:22:15.461',NULL,1,1,'2019-06-14 16:22:15.461','{"ActivityExecutionID":"${ActivityExecutionID}","workflowFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\PentahoFiles\\SampleFileTransformation.ktr","StepToTrigger":2,"workflowType":"Transformation","inputParameters":{"siteFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\Input\\SampleFileTransformation_input.csv","wastageFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\Input\\SampleFileTransformation_input.csv"},"outputParameters":[]}','{"cronExpression":"0 0 0 0 0/0 ? *"}','SCHEDULED');
--INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(2,'dcf61fd2-7556-4f72-823e-d6e7d4659789','End execution',2,'END',TRUE,'2019-06-14 16:22:15.461','END_EXECUTION',1,1,'2019-06-14 16:22:15.461','{}',NULL,'MANUAL');

INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(1,'07167dc7-9a04-4f08-b53e-862c119a3223','SampleDatabaseTranformation',1,'INTEGRATION',TRUE,'2019-06-14 16:28:22.271',NULL,1,1,'2019-06-14 16:28:22.271','{"ActivityExecutionID":"${ActivityExecutionID}","workflowFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\PentahoFiles\\SampleDatabaseTranformation.ktr","StepToTrigger":2,"workflowType":"Transformation","inputParameters":{"siteFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\Input\\SampleDatabaseTranformation_input.csv","wastageFilePath":"${BaseFolderPath}\\Sub_${SubscriberID}\\Proc_${IntegrationProcessID}\\Input\\SampleDatabaseTranformation_input.csv"},"outputParameters":[]}','{"cronExpression":"0 0 0 0 0/0 ? *"}','SCHEDULED');
INSERT INTO activity (ActivityID, ActivityKey, ActivityName, ActivityOrderIndex, ActivityType, CausesNewProcessExecution, CreatedDate, EventGroupName, EventGroupOrderIndex, IntegrationProcessID, ModifiedDate, ProcessingSpecification, ScheduleSetup, TriggerType) VALUES(2,'44437f96-f32c-4fb6-b46b-05cee1229b94','End execution',2,'END',TRUE,'2019-06-14 16:28:22.271','END_EXECUTION',1,1,'2019-06-14 16:28:22.271','{}',NULL,'MANUAL');

 


